<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJGux6ec\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJGux6ec/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJGux6ec.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJGux6ec\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJGux6ec\App_KernelDevDebugContainer([
    'container.build_hash' => 'JGux6ec',
    'container.build_id' => '129dad34',
    'container.build_time' => 1765808134,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJGux6ec');
