<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZDVII0E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZDVII0E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZDVII0E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZDVII0E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZDVII0E\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZDVII0E',
    'container.build_id' => 'eed8fb5e',
    'container.build_time' => 1765491316,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZDVII0E');
